name: akumuslim
description: "A new Flutter project."

publish_to: 'none' 

environment:
  sdk: ^3.13.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  http: ^1.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  flutter_launcher_icons: "^0.13.1"

flutter:
  uses-material-design: true
  assets:
    - assets/
  
flutter_icons:
  android: true
  image_path: "/home/azkaaa/Kuliah/PAPB/akumuslim/akumuslimtest/assets/iconakumuslim.jpeg"